<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Roles.aspx.cs" Inherits="ITCR.Application.Roles" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    
    <asp:Label CssClass="alert-danger" runat="server" ID="lblError" Visible="false"></asp:Label>

    <asp:GridView CssClass="table table-striped" Width="40%" runat="server" ID="RolesGrid" CellSpacing="-1" GridLines="None"
        ItemType="ITCR.Domain.Entities.Role" DataKeyNames="RoleId"
        AutoGenerateColumns="false"
        AllowPaging="true" AllowSorting="true" PageSize="5"
        SelectMethod="RolesGridGetRows" 
        DeleteMethod="RolesGridDelete" AutoGenerateDeleteButton="true"
        UpdateMethod="RolesGridUpdate" AutoGenerateEditButton="true" >
        <Columns>
            <asp:DynamicField DataField="Description" />
        </Columns>
        <EmptyDataTemplate>
            No roles found.
        </EmptyDataTemplate>
        <SortedAscendingHeaderStyle CssClass="asc" />
        <SortedDescendingHeaderStyle CssClass="desc" />
        <PagerStyle CssClass="pager" />
    </asp:GridView>
    <p><b>Add new Role</b></p>
    <asp:TextBox runat="server" ID="txtNewDescription"></asp:TextBox>
    <asp:Button runat="server" ID="btnAddRole" OnClick="btnAddRole_Click" Text="Add role"/>

</asp:Content>
