<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Species.aspx.cs" Inherits="ITCR.Application.Species" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
     
    <asp:Label CssClass="alert-danger" runat="server" ID="lblError" Visible="false"></asp:Label>

    <asp:GridView CssClass="table table-striped" Width="40%" runat="server" ID="SpeciesGrid" CellSpacing="-1" GridLines="None"
        ItemType="ITCR.Domain.Entities.Specie" DataKeyNames="SpecieId"
        AutoGenerateColumns="false"
        AllowPaging="true" AllowSorting="true" PageSize="5"
        SelectMethod="SpeciesGridGetRows" 
        DeleteMethod="SpeciesGridDelete" AutoGenerateDeleteButton="true"
        UpdateMethod="SpeciesGridUpdate" AutoGenerateEditButton="true" >
        <Columns>
            <asp:DynamicField DataField="Description" />
        </Columns>
        <EmptyDataTemplate>
            No species found.
        </EmptyDataTemplate>
        <SortedAscendingHeaderStyle CssClass="asc" />
        <SortedDescendingHeaderStyle CssClass="desc" />
        <PagerStyle CssClass="pager" />
    </asp:GridView>
    
    <p><b>Add new Specie</b></p>
    <asp:TextBox runat="server" ID="txtNewDescription"></asp:TextBox>
    <asp:Button runat="server" ID="btnAddSpecie" OnClick="btnAddSpecie_Click" Text="Add specie"/>
</asp:Content>
